fix(plugin-chart-echarts): table x-filtering support single select
apache-superset/superset-ui pull request #1220
Opened 2021-07-14 15:16 UTC by stephenLYZ

🏆 Enhancements

### before

https://user-images.githubusercontent.com/11830681/125647071-0b284574-5ae9-4821-a586-561001d2d8e3.mov

### after

https://user-images.githubusercontent.com/11830681/125647045-c8c3a122-de96-43d2-8336-2b1dbc3fdb07.mov

2021-07-15 02:38 UTC, ktmud commented
Are we should this is what we want?

A lot of datasources would probably appreciate multi-select more than filtering only by one dimension & one value.

It some users have asked for single select, we should make the filters configurable instead of changing the behavior for all.

2021-07-15 02:39 UTC, ktmud requested changes
Let's make this configurable or support Cmd/Ctr & Shift + Click.

2021-07-19 16:39 UTC, rusackas commented
At this moment, we're aiming for consistency, so a bunch of plugins are being moved to single-select. We can then do a small round of UX/UI design work to figure out the right interaction mechanism, affordance/indication, and means to clear one or all selects. Let's get simple cross-filtering working across he board, then step it up a notch across the board, rather than leaving it mix-and-match

2021-07-19 16:41 UTC, rusackas commented on plugins/plugin-chart-table/src/TableChart.tsx
> +      // mutil select
Maybe worth a bit more of a note as to why these are here. Something like:

> Leaving this code here and commented out, for a future iteration where all (or at least most) plugins will support multi-select cross-filter emission.

2021-07-19 16:42 UTC, rusackas approved these changes

2021-07-19 21:12 UTC, ktmud approved these changes
I'd imagine the code be very different when we do add multi-select support so maybe the comments should be cleaned up instead.

2021-07-20 01:41 UTC, stephenLYZ commented
> I'd imagine the code be very different when we do add multi-select support so maybe the comments should be cleaned up instead.

Agreed, but I think it might be useful to implement multiple-select later. Here I'll remove the comments first.

2021-07-20 03:54 UTC, merged